name: riverplastic
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - jupyter
  - ipykernel
  - pip:
    - geopandas
    - pysheds
    - rasterio
    - xarray
    - zarr
    - cdsapi
    - earthengine-api
    - xgboost
    - lightgbm
    - shap
    - mapie
    - scikit-learn
    - folium
    - cartopy
    - tqdm
    - requests
    - python-dotenv
